steps:
# Build and deploy backend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/call-confirmation-backend', '.']
  dir: 'voiceconfirm-backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/call-confirmation-backend']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'call-confirmation-backend', '--image', 'gcr.io/$PROJECT_ID/call-confirmation-backend', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  dir: 'voiceconfirm-backend'

# Build and deploy frontend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/call-confirmation-frontend', '.']
  dir: 'voiceconfirm-frontend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/call-confirmation-frontend']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'call-confirmation-frontend', '--image', 'gcr.io/$PROJECT_ID/call-confirmation-frontend', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  dir: 'voiceconfirm-frontend'

images:
- 'gcr.io/$PROJECT_ID/call-confirmation-backend'
- 'gcr.io/$PROJECT_ID/call-confirmation-frontend'
